// Build script to generate config.js from .env file
// This script provides security by hashing the answer and encoding the flag

const fs = require('fs');
const crypto = require('crypto');
const path = require('path');

// Read .env file
function parseEnvFile(filePath) {
    const envContent = fs.readFileSync(filePath, 'utf-8');
    const env = {};
    
    envContent.split('\n').forEach(line => {
        line = line.trim();
        if (line && !line.startsWith('#')) {
            const [key, ...valueParts] = line.split('=');
            const value = valueParts.join('=').trim();
            env[key.trim()] = value;
        }
    });
    
    return env;
}

// Hash a string using SHA-256
function hashString(str) {
    return crypto.createHash('sha256').update(str).digest('hex');
}

// Encrypt the flag using the correct answer as the key (AES-256-CBC)
function encryptFlag(flag, key) {
    // Derive a 32-byte key from the answer using SHA-256
    const keyHash = crypto.createHash('sha256').update(key).digest();
    
    // Generate a random IV (Initialization Vector)
    const iv = crypto.randomBytes(16);
    
    // Create cipher
    const cipher = crypto.createCipheriv('aes-256-cbc', keyHash, iv);
    
    // Encrypt the flag
    let encrypted = cipher.update(flag, 'utf8', 'hex');
    encrypted += cipher.final('hex');
    
    // Return IV + encrypted data (we need IV to decrypt)
    return iv.toString('hex') + ':' + encrypted;
}

// Main build function
function build() {
    try {
        console.log('🔨 Building configuration...\n');
        
        // Check if .env exists
        const envPath = path.join(__dirname, '.env');
        if (!fs.existsSync(envPath)) {
            console.error('❌ Error: .env file not found!');
            console.log('Please create a .env file with CORRECT_ANSWER, FLAG, and WORDS');
            process.exit(1);
        }
        
        // Parse .env
        const env = parseEnvFile(envPath);
        
        // Validate required fields
        if (!env.CORRECT_ANSWER || !env.FLAG || !env.WORDS) {
            console.error('❌ Error: Missing required fields in .env file');
            console.log('Required fields: CORRECT_ANSWER, FLAG, WORDS');
            process.exit(1);
        }
        
        // Process data
        const correctAnswer = env.CORRECT_ANSWER;
        const flag = env.FLAG;
        const words = env.WORDS.split(',').map(w => w.trim());
        
        // Generate hash of correct answer
        const correctAnswerHash = hashString(correctAnswer);
        
        // Encrypt flag using the correct answer as the key
        const encryptedFlag = encryptFlag(flag, correctAnswer);
        
        // Display info (without revealing sensitive data)
        console.log('✅ Configuration processed:');
        console.log(`   - Words: ${words.length} words loaded`);
        console.log(`   - Answer hash: ${correctAnswerHash.substring(0, 16)}...`);
        console.log(`   - Flag encrypted with AES-256: ${encryptedFlag.substring(0, 20)}...\n`);
        
        // Generate config.js
        const configContent = `// Auto-generated config file
// DO NOT EDIT MANUALLY - Generated by build.js from .env

const CONFIG = {
    // Shuffled words for the puzzle
    words: ${JSON.stringify(words, null, 4)},
    
    // SHA-256 hash of the correct answer
    correctAnswerHash: '${correctAnswerHash}',
    
    // AES-256 encrypted flag (encrypted with correct answer as key)
    encryptedFlag: '${encryptedFlag}'
};

// Prevent modification
Object.freeze(CONFIG);
`;
        
        // Write config.js
        const configPath = path.join(__dirname, 'config.js');
        fs.writeFileSync(configPath, configContent);
        
        console.log('✅ config.js generated successfully!\n');
        console.log('🚀 You can now open index.html in a browser or deploy to GitHub Pages');
        console.log('⚠️  Remember to add .env to .gitignore before committing!\n');
        
    } catch (error) {
        console.error('❌ Build failed:', error.message);
        process.exit(1);
    }
}

// Run build
build();
