// Auto-generated config file
// DO NOT EDIT MANUALLY - Generated by build.js from .env

const CONFIG = {
    // Shuffled words for the puzzle
    words: [
    "the",
    "quick",
    "brown",
    "fox"
],
    
    // SHA-256 hash of the correct answer
    correctAnswerHash: '9ecb36561341d18eb65484e833efea61edc74b84cf5e6ae1b81c63533e25fc8f',
    
    // AES-256 encrypted flag (encrypted with correct answer as key)
    encryptedFlag: '4f3331959f854d9bf20e39af5b4bbec0:a68630ddc68f89bbbd670ed58648b4cb1ea7b07b29ed09b115f9e6fa51147e633b726185b7c1225fe337c6170e9a9cfc'
};

// Prevent modification
Object.freeze(CONFIG);
